Metrics/MethodLength:
  Max: 20

Style/AsciiComments:
  Enabled: false

Style/ClassCheck:
  Exclude:
    - lib/hairballs/plugin.rb
    - lib/hairballs/plugins/object_ri.rb

Style/Documentation:
  Exclude:
    - lib/hairballs/version.rb

Style/DotPosition:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'

Style/RescueModifier:
  Exclude:
    - lib/hairballs/plugins/colorize_json.rb

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false
